import fs from 'node:fs';
import vm from 'node:vm';
const original=fs.readFileSync('source/original.html','utf8');
const oldTranslations=vm.runInNewContext('('+original.match(/const T=(.*?);function L/s)[1]+')');
const extra=JSON.parse(fs.readFileSync('source/extra-translations.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
let template=original.replace(/<script>[\s\S]*?<\/script>/g,'').replace(/<svg aria-hidden="true"[\s\S]*?<\/svg>/,'');
template=template.replace(/<svg viewBox="0 0 900 520">[\s\S]*?<\/svg>/g,'<img src="/assets/famba-logo.png" alt="FAMBA-SMEs" width="1672" height="941">');
const photo=(file,key)=>`<img src="/assets/${file}.jpg" data-alt="${key}" alt="" width="1400" height="900" loading="lazy" decoding="async">`;
const imageSequence=[['meeting','altMeeting'],['meeting','altMeeting'],['gulf','altGulf'],['industry','altIndustry'],['conference','altConference'],['france','altFrance'],['china','altChina'],['conference','altConference'],['gulf','altGulf'],['industry','altIndustry']];
let imageIndex=0;
template=template.replace(/<svg viewBox="0 0 600 360">[\s\S]*?<\/svg>/g,()=>photo(...imageSequence[imageIndex++]));
if(imageIndex!==imageSequence.length)throw new Error('Unexpected source image count');
template=template.replace('<strong>Growth</strong>','<strong data-k="growth">Growth</strong>').replace('<strong>Trusted</strong>','<strong data-k="trusted">Trust</strong>');
template=template.replace(/<div class="org">.*?<\/div>/,'<div class="org" data-k="org"></div>');
template=template.replace('<div class="line">☎ +86 132 4041 0557</div>','<div class="line"><a dir="ltr" href="tel:+8613240410557">+86 132 4041 0557</a></div>');
template=template.replaceAll('href="mailto:mickael.viudez@gmail.com"','dir="ltr" href="mailto:mickael.viudez@gmail.com"');
let region=0;
template=template.replace(/<div class="pl">[\s\S]*?<\/div>/g,()=>{const i=++region;return `<div class="pl">${i===2?'':photo(['france',null,'china','gulf'][i-1],['altFrance',null,'altChina','altGulf'][i-1])}<strong data-k="rn${i}"></strong><p data-k="rd${i}"></p></div>`;});
template=template.replace('<nav>','<button class="menu-toggle" aria-controls="main-nav" aria-expanded="false" data-k="menu">Menu</button><nav id="main-nav">');
template=template.replace('<body>','<body><a href="#top" class="skip" data-k="skip">Skip to content</a>');
template=template.replace('<main id="top">','<main id="top" tabindex="-1">');
template=template.replace(/<footer>.*?<\/footer>/,'<footer><img src="/assets/famba-logo.png" alt="FAMBA-SMEs" width="1672" height="941" loading="lazy"><div>© 2026 FAMBA-SMEs</div><span data-k="footer"></span><a class="footer-email" dir="ltr" href="mailto:mickael.viudez@gmail.com">mickael.viudez@gmail.com</a></footer>');
template=template.replace('</head>','<link rel="icon" href="/assets/famba-logo.png"><link rel="stylesheet" href="/assets/refinements.css"></head>');
template=template.replace('</body>','<script src="/assets/navigation.js" defer></script></body>');
const base={};
for(const m of template.matchAll(/<([a-z0-9]+)([^>]*data-k="([^"]+)"[^>]*)>([^<]*)<\/\1>/g))base[m[3]]=m[4].replaceAll('&amp;','&');
fs.mkdirSync('dist',{recursive:true});
fs.cpSync('assets','dist/assets',{recursive:true});
fs.copyFileSync('source/refinements.css','dist/assets/refinements.css');
fs.copyFileSync('source/navigation.js','dist/assets/navigation.js');
const urls={en:'/',fr:'/fr/',zh:'/zh/',ar:'/ar/'};
const names={en:'English',fr:'Français',zh:'中文',ar:'العربية'};
for(const lang of Object.keys(urls)){
  const t={...base,...(oldTranslations[lang]||{}),...extra[lang]};
  let html=template.replace('<html lang="en">',`<html lang="${lang==='zh'?'zh-CN':lang}" dir="${lang==='ar'?'rtl':'ltr'}">`);
  html=html.replace(/<button class="lg[^>]*data-lang="([^"]+)"[^>]*>.*?<\/button>/g,(_,code)=>`<a class="lg${code===lang?' active':''}" href="${urls[code]}" lang="${code}" hreflang="${code==='zh'?'zh-CN':code}"${code===lang?' aria-current="page"':''}>${names[code]}</a>`);
  html=html.replace(/<([a-z0-9]+)([^>]*data-k="([^"]+)"[^>]*)>([^<]*)<\/\1>/g,(_,tag,attrs,key)=>{if(t[key]===undefined)throw new Error(`Missing ${lang}:${key}`);return `<${tag}${attrs}>${esc(t[key])}</${tag}>`;});
  html=html.replace(/data-alt="([^"]+)" alt=""/g,(_,key)=>`alt="${esc(t[key])}"`);
  html=html.replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(t.desc)}">`);
  html=html.replace('<title>FAMBA-SMEs</title>',`<title>FAMBA-SMEs — ${esc(t.wt)}</title><link rel="canonical" href="https://sme-famba.com${urls[lang]}">${Object.entries(urls).map(([l,u])=>`<link rel="alternate" hreflang="${l==='zh'?'zh-CN':l}" href="https://sme-famba.com${u}">`).join('')}<link rel="alternate" hreflang="x-default" href="https://sme-famba.com/">`);
  html=html.replace('href="mailto:mickael.viudez@gmail.com?subject=FAMBA-SMEs Membership"',`href="mailto:mickael.viudez@gmail.com?subject=${encodeURIComponent('FAMBA-SMEs — '+t.j)}"`);
  html=html.replace('<div class="gal">',`<p class="photo-note">${esc(t.photoNote)}</p><div class="gal">`);
  const field=(key,type='text')=>`<label${key==='company'?' class="full"':''} for="${key}">${esc(t[key])}<input id="${key}" name="${key}" type="${type}" ${key==='company'?'':'required'} maxlength="${key==='email'?254:180}" autocomplete="${key==='company'?'organization':key}"${key==='email'?' dir="ltr"':''}></label>`;
  const form=`<div class="w"><form class="contact-form" action="https://formsubmit.co/mickael.viudez@gmail.com" method="POST"><h2>${esc(t.contactTitle)}</h2><input type="hidden" name="_subject" value="FAMBA-SMEs website enquiry (${lang})"><input type="hidden" name="_next" value="https://sme-famba.com${urls[lang]}thanks.html"><input type="hidden" name="language" value="${lang}"><input class="honeypot" type="text" name="_honey" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="fields">${field('name')}${field('email','email')}${field('company')}<label class="full" for="message">${esc(t.message)}<textarea id="message" name="message" required maxlength="10000"></textarea></label><div class="full"><button class="send" type="submit">${esc(t.send)}</button></div></div><p class="form-note">${esc(t.formNote)}</p></form></div>`;
  html=html.replace('</section></main>',`${form}</section></main>`);
  const dir='dist'+(lang==='en'?'':`/${lang}`);fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(`${dir}/index.html`,html);
  fs.writeFileSync(`${dir}/thanks.html`,`<!doctype html><html lang="${lang==='zh'?'zh-CN':lang}" dir="${lang==='ar'?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${esc(t.thanks)} — FAMBA-SMEs</title></head><body style="font:18px/1.7 Arial,sans-serif;margin:60px auto;padding:24px;max-width:700px;color:#062d63"><img src="/assets/famba-logo.png" alt="FAMBA-SMEs" width="240"><h1>${esc(t.thanks)}</h1><p>${esc(t.thanksText)}</p><a href="${urls[lang]}">${esc(t.back)}</a></body></html>`);
}
fs.writeFileSync('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: https://sme-famba.com/sitemap.xml\n');
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.values(urls).map(u=>`<url><loc>https://sme-famba.com${u}</loc></url>`).join('')}</urlset>`);
console.log('Built English, French, Chinese and Arabic pages with local assets.');
